### ISSUE TITLE
don't print errors/debug to STDOUT

### ISSUE THREAD

**Issue by garfieldnate** [hrzafer/nuve#61]
When I create a `WordAnalyzer` instance, the following gets printed to STDOUT:

    Duplicate key: SIFAT+BAGLAC_dA
    Duplicate key: ZAMAN_ki+BAGLAC_dA
    Duplicate key: FC_YF_YETERSIZLIK_(y)AmA+FC_YF_YETERLILIK_(y)Abil
    Duplicate key: FIILIMSI_ISIM_mA+IY_ISIM_CU
    Duplicate key: FIILIMSI_ISIM_mA+EKFIIL_TANIMLAMA_DUr

These debug messages would be better in STDERR. For now, I am preventing this extra printing by temporarily changing Console.Out: `Console.SetOut(TextWriter.Null);`.

**Comment by hrzafer** [comment]
I'm planning to use a logging framework soon. Those messages and more will be handled by that framework then. I'm keeping this issue as a reminder.

**Comment by hrzafer** [comment]
Debug messages are moved to Debug.Print()
