### ISSUE TITLE
analysis/generation API asymmetry for roots

### ISSUE THREAD

**Issue by garfieldnate** [hrzafer/nuve#63]
There is currently an asymmetry that makes the analysis/generation process more awkward than it should be. As an example string, take "normal kusuru" (sorry, I know it's nonsense). Wanting to do analysis and regeneration later, I thought that the tagged form would suffice:

    normál/SIFAT kusur/ISIM sU/IC_SAHIPLIK_O_(s)U

For generation, I take the above information and use `turkish.GetRootsHavingSurface(surface)` for strings that have a root tag (SIFAT, ISIM, etc.), and `turkish.GetSuffix(tag)` for other stuff. For roots you need the surface, and for suffixes you need the tag. However, this tagged form contains a lexical form that may be different from the surface form (like normál above). So when I save an analysis for regeneration later I have to do custom processing to get something like this:

    normal/SIFAT...

And then I have to search through the roots returned from `turkish.GetRootsHavingSurface(surface)` for the correct one:

	using (IEnumerator<Root> enumer = tr.GetRootsHavingSurface (surface).GetEnumerator()) {
		while (enumer.MoveNext ()) {
			String taggedForm = enumer.Current.TaggedForm;
			if(Regex.IsMatch(taggedForm, "/" + tag)){
				return enumer.Current;
			}
		}
	}

That's more complicated than it should be. It would be nice to have a single method `Language.GetMorphemeFromTaggedForm(taggedForm)`. Then the user could give it `normál/SIFAT` and it would return a root or `sU/IC_SAHIPLIK_O_(s)U` and it would return a suffix. The user would have to cast from Morpheme to Root or Suffix after checking the type, but that isn't so bad.

**Comment by garfieldnate** [comment]
So it turns out the "custom processing" I do to get `normal/SIFAT` does not always work. I am simply doing `allomorph.Surface`, but this gives the surface as actually found in the text. Unfortunately, allomorph.Morpheme.Surface always comes back null. So I don't think I have any way of recovering roots with the current state.

**Comment by garfieldnate** [comment]
I created a workaround after analyzing root.txt. The method below will provide the surface form corresponding to a lexical form:

		//workaround because Nuve requires the surface form for generation but only provides the
		//lexical form from analysis; figured out by analyzing Nuve's root.txt.
		private static Dictionary<String, String> lexicalToSurface = new Dictionary<String, String>(){
			{"lex", "root"},
			{"Âdem", "Adem"},
			{"arzuhál", "arzuhâl"},
			{"eşkál", "eşkâl"},
			{"hál", "hâl"},
			{"hasbihál", "hasbihâl"},
			{"hemhál", "hemhâl"},
			{"hüsnühál", "hüsnühâl"},
			{"iy", "i"},
			{"ilmihál", "ilmihâl"},
			{"işkál", "işkâl"},
			{"itikál", "itikâl"},
			{"lisanıhál", "lisanıhâl"},
			{"of", "Of"},
			{"tercümeihál", "tercümeihâl"},
			{"usúl", "usûl"},
			{"yár", "yâr"}
		};
		private String FixRootLemma(String lexForm){
			String surface;
			if (lexicalToSurface.TryGetValue(lexForm, out surface)){
				return surface;
			}
			surface = lexForm;
			surface = Regex.Replace (surface, "î", "i");
			surface = Regex.Replace (surface, "â", "a");
			surface = Regex.Replace (surface, "á", "a");
			surface = Regex.Replace (surface, "ó", "o");
			surface = Regex.Replace (surface, "ú", "u");
			surface = Regex.Replace (surface, "û", "u");
			return surface;
		}

**Comment by hrzafer** [comment]
I understand the problem. For suffixes tag id is unique. For roots it is a bit complicated. Even lex/tag combinations may not be unique. So, I can not guarantee  getMorphemeFromTaggedForm(taggedForm) returns a single root at this time. However you are right about the API inconsistency and I'll try to redesign it as soon as I have some time. I also plan to add a method which can generate the whole word from its tagged form. Something like:

```C# 
Word w = languge.generate("normál/SIFAT yA/IC_HAL_YONELME_(y)A");
```

**Comment by hrzafer** [comment]
With the version 1.5.0 API is changed to provide a more consistency and ease of use. Please refer to the readme.MD

**Comment by garfieldnate** [comment]
Thanks. Looks like you've been busy during holiday break!
