### ISSUE TITLE
GUI relies on hardcoded paths from your computer

### ISSUE THREAD

**Issue by garfieldnate** [hrzafer/nuve#64]
I can't run the GUI project because of paths like `C:\Users\harun_000\Desktop\vboxshare\paragraphs-no-punctuation_trimmed.txt` hardcoded into program.cs; the program dies immediately because it cannot find the files.

**Comment by hrzafer** [comment]
Actually there is no GUI. Sorry for the misleading naming. Program.cs is the main class where I try, test anything. In the main method, you can comment out anything except the test(); In the test method you can test several words.
