### ISSUE TITLE
missed words

### ISSUE THREAD

**Issue by garfieldnate** [hrzafer/nuve#71]
I do not speak Turkish, so I cannot be sure, but I found the following words that Nuve could not analyze:

* hammaddesini -> hammadde
* çevirilir -> çevir
* japoncasına -> japon
* vulkanizatöre -> vulkanize
* ortayan -> ortaya?

Actually `japoncasına` is strange because Nuve 1.3.2 on my computer gives 0 analyses, but the Nuve demo online gives several.

**Comment by hrzafer** [comment]
* hammadde: is a compound word, TDK says that it should be written as "ham madde".
* çev(i)rilir -> çevrilir. This is a Turkish orthographic rule. The i in the paranthesis is dropped. Other examples are burun+u => burnu, ağız+ı => ağzı
* Japon (Japanese) is a proper noun, J should be capital. (Demo runs also runs 1.3.2 version)
* vulkanize, vulkanizatör: Never heard of them!
* ortayan: Never heard of it either, maybe a misspell, "orta" means "middle",  ortaya means "to middle"

**Comment by garfieldnate** [comment]
Okay, I understand the problem for Japoncasına, and it relates to #62. To do thorough segmentation, I need to try lookup via both upper and lowercase (I don't have any way of finding proper nouns). There's not much to be done about rare words, compounds, or incorrect Turkish. Is "çevirilir" an incorrect spelling or is it just an alternative spelling?

**Comment by hrzafer** [comment]
"çevrilir" is a common misspelling. 

For misspellings a simple spellchecker could work. You can use NHunspell and I can provide Turkish dictionary files for it. If a word cannot be analyzed by Nüve, you can get a suggestion from NHunspell and give it to Nüve.

**Comment by garfieldnate** [comment]
Yes, a Turkish spelling dictionary would be great, thanks. I am surprised
to find misspellings in an expensive translated data set!

On Tue, Oct 20, 2015 at 2:20 PM, Harun Reşit Zafer <notifications@github.com
