### ISSUE TITLE
letter analysis is irreversible

### ISSUE THREAD

**Issue by garfieldnate** [hrzafer/nuve#73]
The analysis for many letters gives back a name different than the letter itself; for example, `f` -> `fe/HARF`. This cannot be reversed again later using `tr.GetRootsHavingSurface('fe')`, and I don't see anything like `tr.GetAbbreviationsHavingSurface(string)` either. Because of this, letters are irreversibly turned into spellings of their pronunciations: fe, ge, he, etc.

**Comment by hrzafer** [comment]
"fe" is the lexical form for the word "f" (single letters are considered as words in this case). And "f" is its surface form. Use `tr.GetRootsHavingSurface("f").First()` instead and consider the following code:

```C#
var root = Language.Turkish.GetRootsHavingSurface("f").First();
Word word = new Word(root);
Console.WriteLine(root); //returns a string for debug purposes
Console.WriteLine(word);//returns a string for debug purposes
Console.WriteLine(word.GetSurface()); // returns f
```

I'll fix and document the API ASAP.
