### ISSUE TITLE
Can't create a Language class

### ISSUE THREAD

**Issue by yusuf-gunaydin** [hrzafer/nuve#75]
Why is the `LanguageFactory` class marked as internal? Documentation states that the `Language` class is instantiated via `LanguageFactory`, but I can't access that class.

I am using 1.5.0 via Nuget.

**Comment by hrzafer** [comment]
Sorry. I made the internals visible to the client project (Nuve.Gui) for some reason. That's why my code compiled and I couldn't see that. Now I remove the ``[assembly: InternalsVisibleTo("Nuve.Gui")]`` not to repeat the same mistake. I also pushed a new version 1.5.1 to Nuget.

**Comment by yusuf-gunaydin** [comment]
Thanks.

**Comment by hrzafer** [comment]
The commit that fixes the issue: https://github.com/hrzafer/nuve/commit/edb51baed854ab1cac0647cad4c5f594ce0fd4dc
