### ISSUE TITLE
Sentence Segmentation - 'Not a valid Roman numeral'

### ISSUE THREAD

**Issue by rawk10** [hrzafer/nuve#76]
While trying your default examples from ReadMe file, the Sentence Segmentation method throwed an exception: 
`An unhandled exception of type 'System.ArgumentException' occurred in Nuve.dll`
`Additional information: Not a valid Roman numeral: kez  `

The input sentence is unchanged default: 
> "Prof. Dr. Ahmet Bey 1.6 oranında artış var dedi 2. kez. E-posta adresi ahmet.bilir@prof.dr imiş! Doğru mu?"

_Platform: Windows 7, VS Community 2015_

**Comment by hrzafer** [comment]
Fixed and will be available with the next release. Thanks for the feedback.
