### ISSUE TITLE
Root Solutions

### ISSUE THREAD

**Issue by onur-keles** [hrzafer/nuve#79]
The program does not give solution for the word "evet" although its online version gives EDAT solution. Similar situation occurs for "için", "eğer", "ve", "de", "madem", "veya" and "veyahut".
![no solution found evet](https://cloud.githubusercontent.com/assets/18612001/14742944/72aa6f68-08a7-11e6-8fda-901eb24a973e.jpg)
![icin](https://cloud.githubusercontent.com/assets/18612001/14742945/72acd38e-08a7-11e6-9658-9462020f583b.jpg)

**Comment by hrzafer** [comment]
Fixed. Thank you for feedback.
