### ISSUE TITLE
Words list that Nuve fails to analyze

### ISSUE THREAD

**Issue by MonsterMMORPG** [hrzafer/nuve#84]
I have analyzed over 1.3m unique words generated by using spell checker dictionary files

Here the words that the nuve failed to analyze. I have ignored words that contains **'**

Word list is attached it is 9948 lines

[failed_to_parse.txt](https://github.com/hrzafer/nuve/files/834932/failed_to_parse.txt)

**Comment by hrzafer** [comment]
Hi,

Thanks for the feedback. I've reviewed the list. However, none of the words is valid. Most of the words in the list requires an `'` to be valid. Such as `ABD'de` and `AB'yi`. Also more than 3000 words has the letter 'ý', 850 words have the letter `þ`, and 368 words have `þ`  in them. These letters does not exist in the. Turkish alphabet.

For the  `ABD'de` example, I agree that the analyzer could be more tolerable. But current design does not allow that.
