### ISSUE TITLE
FY_OLUMSUZLUK_mA comes always after FIIL?

### ISSUE THREAD

**Issue by MonsterMMORPG** [hrzafer/nuve#86]
Hello. Can we assume this to make verb conjugations negative always?

For example

FIIL;FC_KIP_GEREKLILIK_mAlI;EKFIIL_SART_(y)sA;EKFIIL_SAHIS_SEN_n:
//çal > malı > ysa > n

FIIL;FY_OLUMSUZLUK_mA;FC_KIP_GEREKLILIK_mAlI;EKFIIL_SART_(y)sA;EKFIIL_SAHIS_SEN_n

//çal > ma > malı > ysa > n

So adding after root **FIIL** `FY_OLUMSUZLUK_mA` would make always negative?

And can we assume that all root verbs can get all 197 conjugations? 

Actually i have found an error in single case

In case of 

çalarız > çalmayız

It has automatically generated as

çalarız > çalmazız

The used suffix list is

```
çal+
FY_OLUMSUZLUK_mA
FC_ZAMAN_GENIS_(U)r
EKFIIL_SAHIS_BIZ_(y)Uz
```

**Comment by hrzafer** [comment]
Yes. But there are minor exceptions for some rarely used suffixes such as `-e durmak`, `-e yazmak`. 
Examples are, `yapadurdu`, `yapadurmadi`, `yapmayadurdu`. I really don't know which one of the negative cases is correct.

**Comment by MonsterMMORPG** [comment]
@hrzafer  ty very much for the answer

By the way i have fixed that error by making a single case check <> fix

çalarız > çalmazız i mean
